### ISSUE TITLE
Old and useless code, doesn't grant access to EdgyBot and is full of bugs. Authentic EdgyBot already 10 versions ahead with many new feature additions and bug fixes👎

### ISSUE THREAD

**Issue by GSRHackZ** [wearrrrr/EdgyNukeDeobfuscationProject#2]
This supposedly unobfuscated version is old and buggy and doesn't work properly. Also when you try to use it, the EdgePlus payment screen still appears and doesn't grant access to the bot.  Newer versions of the script now have better purchase verification.

Try getting though those 😹😹

**Comment by wearrrrr** [comment]
Challenge accepted :)

also by 10 versions you mean 10 MINOR version increments ahead, fyi, look up how to do proper version naming ;)

**Comment by wearrrrr** [comment]
also this is your code so if its buggy, uhh your bad lol

**Comment by wearrrrr** [comment]
done xd @GSRHackZ 

I did indeed get through your "better" purchase verification `ヾ(￣▽￣) Bye~Bye~`
