### ISSUE TITLE
Bot doesn't grant access anymore, still locked and displays EdgePlus "awaiting verification"

### ISSUE THREAD

**Issue by executive-decision** [wearrrrr/EdgyNukeDeobfuscationProject#3]
The bot somehow locked and no longer opens anymore?? It's saying "awaiting purchase verification" and a popup message said "Inauthentic edgybot detected 😣"

**Comment by wearrrrr** [comment]
Still works perfectly fine for me, try readding the script through tampermonkey.

**Comment by ItsZnake** [comment]
yo does it still work ? for me it its awaiting purchase verification  and i used tamper monkey rip

**Comment by GSRHackZ** [comment]
wow, ur fast. I would like to pay you for a project, $200.

contact my email gsrhackz@gmail.com

**Comment by GSRHackZ** [comment]
@wearrrrr

**Comment by ItsZnake** [comment]
Yo @wearrrrr if you accept his project make sure he legit pays lmfao your too cracked

**Comment by GSRHackZ** [comment]
nah cuz that was valid. I have a program for him to crack, i'll pay before receiving the product to ensure he gets paid 👌

**Comment by ItsZnake** [comment]
Bro is a fucking chad he told you he was gonna get passed your shit and didn’t front what a fucking chad

**Comment by wearrrrr** [comment]
> wow, ur fast. I would like to pay you for a project, $200.
> 
> contact my email [gsrhackz@gmail.com](mailto:gsrhackz@gmail.com)

I'm mostly only good at javascript reverse engineering, so depending on the project I might not be able to do it, but i'll give you an email rq

**Comment by GSRHackZ** [comment]
> > wow, ur fast. I would like to pay you for a project, $200.
> 
> > 
> 
> > contact my email [gsrhackz@gmail.com](mailto:gsrhackz@gmail.com)
> 
> 
> 
> I'm mostly only good at javascript reverse engineering, so depending on the project I might not be able to do it, but i'll give you an email rq

Thank you 🙏
